foreground                      #D8DEE9
background                      #0B0F14
selection_foreground            #ECEFF4
selection_background            #3B4656

cursor                          #ECEFF4
cursor_text_color               #0B0F14

active_tab_foreground           #ECEFF4
active_tab_background           #5E81AC
inactive_tab_foreground         #AAB4C3
inactive_tab_background         #151B23

# black
color0 #151B23
color8 #3B4656

# red
color1 #BF616A
color9 #D06F79

# green
color2  #A3BE8C
color10 #B1C89A

# yellow
color3  #EBCB8B
color11 #F0D49A

# blue
color4  #81A1C1
color12 #88C0D0

# magenta
color5  #B48EAD
color13 #C09ABD

# cyan
color6  #8FBCBB
color14 #9ACBC9

# white
color7  #D8DEE9
color15 #ECEFF4
